# Coding Assignment

Create a simple **Student Report Card** program.

Requirements:

* Store a student's name and marks in three subjects.
* Calculate the total and average.
* Print whether the student passed (average ≥ 50).
* Organize your code by writing a function that computes the average.

---

In [1]:
def average(x):
    total = 0
    for i in x:
        total += i
    return total / len(x) 

student_name = "Siddharth"
marks = [80, 85, 90]
average_marks = average(marks)
print(average_marks)
if average_marks >= 50:
    print("Passed")




85.0
Passed


# Coding Assignment

Create a NumPy array representing the heights (in cm) of 10 students.

Then:

1. Print the array.
2. Print its shape.
3. Add 2 cm to every height.
4. Print the updated array.
5. Print the tallest height using NumPy.

In [2]:
import numpy as np
heights = np.array([180, 176, 170, 192, 155, 162, 172, 188, 178, 160])
print(heights)
print(heights.shape)
heights += 2 
print(heights)
print(np.max(heights))


[180 176 170 192 155 162 172 188 178 160]
(10,)
[182 178 172 194 157 164 174 190 180 162]
194


# Coding Assignment

Using NumPy:

1. Create vectors for the marks of two students in three subjects.
2. Add the vectors.
3. Multiply one vector by `2`.
4. Print all results.
5. Print the shape of each vector.


In [3]:
import numpy as np

# Create a NumPy array representing the heights (in cm) of 10 students
heights = np.array([180, 176, 170, 192, 155, 162, 172, 188, 178, 160])

# 1. Print the array
print("1. Original heights array:")
print(heights)

# 2. Print its shape
print("\n2. Array shape:")
print(heights.shape)

# 3. Add 2 cm to every height (Broadcasting)
heights += 2 

# 4. Print the updated array
print("\n4. Updated heights (after adding 2 cm):")
print(heights)

# 5. Print the tallest height using NumPy
print("\n5. Tallest height:")
print(np.max(heights))

1. Original heights array:
[180 176 170 192 155 162 172 188 178 160]

2. Array shape:
(10,)

4. Updated heights (after adding 2 cm):
[182 178 172 194 157 164 174 190 180 162]

5. Tallest height:
194


# Coding Assignment

Create a dataset of **five students** with these features:

* Hours Studied
* Attendance
* Assignments Completed

Store them in a NumPy matrix called `X`.

Then:

1. Print the matrix.
2. Print its shape.
3. Print the second student's data.
4. Print the attendance column.
5. Add `1` to every assignment count.


In [1]:
import numpy as np 

X = np.array([
    [8, 80, 14],
    [9, 81, 17], 
    [3, 67, 7],
    [5, 58, 10],
    [10, 100, 15]
])

print(X)
print(f"X-shape: {X.shape}")
print(f"Second Student's data: {X[1]}")
print(f"Attendence Column: {X[:, 1]}")

X[:, 2] += 1
print(X)

[[  8  80  14]
 [  9  81  17]
 [  3  67   7]
 [  5  58  10]
 [ 10 100  15]]
X-shape: (5, 3)
Second Student's data: [ 9 81 17]
Attendence Column: [ 80  81  67  58 100]
[[  8  80  15]
 [  9  81  18]
 [  3  67   8]
 [  5  58  11]
 [ 10 100  16]]
